clean up make-release script

diff --git a/src/scripts/make-release b/src/scripts/make-release
--- a/src/scripts/make-release
+++ b/src/scripts/make-release
@@ -2,101 +2,42 @@
 
 # script to make a release, suitable for github
 
-logEnabled=${FVMR_LOG_ENABLED:=1}
-cleanupEnabled=${FVMR_CLEANUP_ENABLED:=1}
-homeDir=${FVMR_HOME_DIR:=$HOME/workspaces/java8/WinlinkFormViewer}
 
-###############################################################################
-## log messages to console
-###############################################################################
-function log() {
-    if [[ $logEnabled == 1 ]]
-    then
-        echo $*
-    fi
-}
+pushd . > /dev/null
+trap "popd > /dev/null" INT
+echo "begin make-release"
+cd ../.. 
+version=$(grep -a -m 1 -h version pom.xml |cut -d '>' -f 2|cut -d '<' -f 1)
 
-###############################################################################
-## cleanup after processing
-###############################################################################
-function cleanup() {
-    	if [[ $cleanupEnabled == 1 ]]
-    	then
-		log "begin cleanup"
- 
-	    	log "end cleanup"
-    	fi
-      	
+if [[ "$version" = "" ]]; then
+	echo "ERROR: couldn't get version, exiting."
 	popd > /dev/null
-    	exit 0
-}
+	exit 1
+else
+	echo "creating release version: $version"
+fi
 
-###############################################################################
-## getVersion
-###############################################################################
-function getVersion() {
-	local version=""
-
-	version=$(grep -a -m 1 -h version pom.xml |cut -d '>' -f 2|cut -d '<' -f 1)
-	echo $version
-}
-
-#######################################################################
-## main
-#######################################################################
-
-function main() {
-	#set -x
-	pushd . > /dev/null
-	trap "stty echo && popd > /dev/null && cleanup" INT
-	log "begin make-release"
-
-    	if [[ ! -e $homeDir ]]
-    	then
-        	echo "ERROR: homeDir: $homeDir does not exist, exiting"
-		cleanup
-    	else
-        	log "using homeDir $homeDir"
-		cd $homeDir
-    	fi
-
-	local version=$(getVersion)
-	if [[ "$version" = "" ]]
-	then
-		echo "ERROR: couldn't get version, exiting."
-		cleanup
-	else
-		echo "creating version: $version"
-	fi
-
-	# basic assembly
-	packageDir="target/appassembler"
-	rm -rf "$packageDir"
-	mvn package -DskipTests=true
-    	if [[ ! -e "$packageDir" ]]
-    	then
-        	echo "ERROR: packing failed, exiting."
-		cleanup
-    	else
-        	log "using homeDir $homeDir"
-		cd $homeDir
-    	fi
-
-	# copy some extra files
-	cp Configuration.md "$packageDir"
-	cp README.md "$packageDir"
-	cp src/scripts/launch* "$packageDir"/bin
-
-	pushd "$packageDir" > /dev/null
-	zip -r "fv-$version".zip *
-	ls -ls *.zip
+# basic assembly
+packageDir="target/appassembler"
+rm -rf "$packageDir"
+mvn package -DskipTests=true
+if [[ ! -e "$packageDir" ]]; then
+	echo "ERROR: packing failed, exiting."
 	popd > /dev/null
+	exit 1
+fi
 
+# copy some extra files
+cp Configuration.md "$packageDir"
+cp README.md "$packageDir"
+cp src/scripts/launch* "$packageDir"/bin
 
-	log "end make-release"
-	cleanup
-}
+pushd "$packageDir" > /dev/null
+zip -r "fv-$version".zip *
+mv *.zip ../..
+popd > /dev/null
+ls -l *.zip
 
-main $*
-
-
+popd > /dev/null
+echo "end make-release"
+exit 0
